### ISSUE TITLE
Is this project currently maintained?

### ISSUE THREAD

**Issue by abarazal** [amanshuraikwar/MaterialStepper#1]
Since last commit was 4 years ago... Is this project currently maintained?

**Comment by amanshuraikwar** [comment]
@abarazal This project is no longer maintained.

**Comment by Dave181295** [comment]
Oh no, please maintain  it again you have a cool library !

**Comment by amanshuraikwar** [comment]
Hi @Dave181295, due to unavailability of resources on my end, I am no longer able to maintain this library. Feel free to fork and improve/maintain the library if required. 

Thanks.

**Comment by Dave181295** [comment]
Hello, thanks for answer, actually I searched a solution for a little problem. is there any way to make the steps not move on next Fragment? so user can see all the steps 1,2,3 etc..
